export default {
    "sushiswap": require("../../adaptors/sushiswap"),
    "mooniswap": require("../../adaptors/mooniswap"),
    "uniswap": require("../../adaptors/uniswap"),
    "spookyswap": require("../../adaptors/spookyswap"),
    "traderjoe": require("../../adaptors/traderjoe"),
    "pancakeswap": require("../../adaptors/pancakeswap"),
    "balancer": require("../../adaptors/balancer"),
    "makerdao": require("../../adaptors/makerdao"),
    "bsc": require("../../adaptors/bsc"), 
    "aave": require("../../adaptors/aave"), 
    "compound": require("../../adaptors/compound"), 
    "osmosis": require("../../adaptors/osmosis"), 
    "gmx": require("../../adaptors/gmx"), 
    "synthetix": require("../../adaptors/synthetix"), 
    "lido": require("../../adaptors/lido"), 
    "curve": require("../../adaptors/curve"), 
    "convex": require("../../adaptors/convex"), 
    "looksrare": require("../../adaptors/looksrare"), 
    "pangolin": require("../../adaptors/pangolin"),
    "quickswap": require("../../adaptors/quickswap"),
    "velodrome": require("../../adaptors/velodrome"),
    "ethereum": require("../../adaptors/ethereum"),
}